### ISSUE TITLE
Bug: Jsonp callbackName can be longer than 32 chars

### ISSUE THREAD

**Issue by hn0pw** [apioo/psx-data#1]
The jsonp writer accepts only a callback name which is shorter than 33 chars.
But with jQuery 2.1.3 the callback can be longer (ex. `jQuery213040548181975297726_1486482323181`).

Why is there the limit set to 32?
```
        if (preg_match('/^([A-Za-z0-9._]{3,32})$/', $callbackName)) {
            $this->callbackName = $callbackName;
        }
```

Please see in this file:
https://github.com/apioo/psx-data/blob/f3b3ead7378b136a7c9bbe5ef83701741984c25a/src/Writer/Jsonp.php#L66

**Comment by hn0pw** [comment]
I tried to replace temporary the jsonp writer with a own class, but this isn't working.
The default jsonp class is automatically used, how can i set my own writer class for jsonp?

And how can i set the jsonp writer if `callback` argument is present?

**Comment by chriskapp** [comment]
Hi, so basically the limit is just there to prevent abusing extreme long names,
there was no concrete reasoning for 32. I will increase the limit to 64 for the next 
release.

Regarding the writer, you have to create a custom `Configuration` where the
writer factory contains your writer. Then in the `ControllerAbstract` there is
a hook method `configureWriter(WriterInterface $writer)` where you can pass
parameters from the request to the writer i.e. the get parameter "callback".

**Comment by hn0pw** [comment]
Thank you for the fix.
